### ISSUE TITLE
Pip-install fails

### ISSUE THREAD

**Issue by siddancha** [mhamilton723/FeatUp#46]
When following the install instructions and running:
```bash
pip install git+https://github.com/mhamilton723/FeatUp
```

I get the following error:

**OS**: Ubuntu 22.04
**Python**: 3.10

```text
Collecting git+https://github.com/mhamilton723/FeatUp
  Cloning https://github.com/mhamilton723/FeatUp to /tmp/pip-req-build-woni10iy
  Running command git clone --filter=blob:none --quiet https://github.com/mhamilton723/FeatUp /tmp/pip-req-build-woni10iy
  Resolved https://github.com/mhamilton723/FeatUp to commit a5f9f56a973573a99504c09a69561f726dbe9d82
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-woni10iy/setup.py", line 2, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mhamilton723** [comment]
try installing pytorch first accourding to 
https://pytorch.org/get-started/locally/
