### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by JaYzZ** [mhamilton723/FeatUp#57]
[featup_err.txt](https://github.com/mhamilton723/FeatUp/files/15272523/featup_err.txt)

Any idea on why this error attached is happening during pip install? Here are the key conda environment components:

|Name|Version|Build|Channel|
|------|------|------|------|
|_libgcc_mutex|0.1|main|defaults|
|_openmp_mutex|5.1|1_gnu|defaults|
|blas|1.0|mkl|defaults|
|clip|1.0|pypi_0|pypi|
|clip-benchmark|1.6.1|pypi_0|pypi|
|cuda-cudart|11.8.89|0|nvidia|
|cuda-cupti|11.8.87|0|nvidia|
|cuda-libraries|11.8.0|0|nvidia|
|cuda-nvrtc|11.8.89|0|nvidia|
|cuda-nvtx|11.8.86|0|nvidia|
|cuda-runtime|11.8.0|0|nvidia|
|intel-openmp|2023.1.0|hdb19cb5_46306|defaults|
|kornia|0.7.2|pypi_0|pypi|
|kornia-rs|0.1.3|pypi_0|pypi|
|libcublas|11.11.3.6|0|nvidia|
|libcufft|10.9.0.58|0|nvidia|
|libcufile|1.9.0.20|0|nvidia|
|libcurand|10.3.5.119|0|nvidia|
|libcusolver|11.4.1.48|0|nvidia|
|libcusparse|11.7.5.86|0|nvidia|
|llvm-openmp|14.0.6|h9e868ea_0|defaults|
|mkl|2023.1.0|h213fc3f_46344|defaults|
|mkl-service|2.4.0|py39h5eee18b_1|defaults|
|mkl_fft|1.3.8|py39h5eee18b_0|defaults|
|mkl_random|1.2.4|py39hdb19cb5_0|defaults|
|ninja|1.11.1.1|pypi_0|pypi|
|nvidia-ml-py|12.535.133|pypi_0|pypi|
|pip|23.3.1|py39h06a4308_0|defaults|
|python|3.9.18|h955ad1f_0|defaults|
|pytorch|2.2.2|py3.9_cuda11.8_cudnn8.7.0_0|pytorch|
|pytorch-cuda|11.8|h7e8668a_5|pytorch|
|pytorch-lightning|2.1.3|pypi_0|pypi|
|pytorch-mutex|1.0|cuda|pytorch|
|setuptools|68.0.0|py39h06a4308_0|defaults|
|tensorboard|2.15.1|pypi_0|pypi|
|tensorboard-data-server|0.7.2|pypi_0|pypi|
|timm|0.9.16|pypi_0|pypi|
|torch-kmeans|0.2.0|pypi_0|pypi|
|torchmetrics|1.2.1|pypi_0|pypi|
|torchtriton|2.2.0|py39|pytorch|
|torchvision|0.17.2|py39_cu118|pytorch|
|wheel|0.41.2|py39h06a4308_0|defaults|
|xformers|0.0.25.post1|py39_cu11.8.0_pyt2.2.2|xformers|

**Comment by jackedney** [comment]
You've installed pytorch compiled with CUDA 11.8 when your machine is running CUDA v11.1

Try updating CUDA on your machine to 11.8

**Comment by Flock1** [comment]
Hi,

I am getting this error:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sarvagya-pc/Desktop/FeatUp/setup.py", line 34, in <module>
          CUDAExtension(
        File "/home/sarvagya-pc/miniconda3/envs/featup/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1078, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/sarvagya-pc/miniconda3/envs/featup/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1209, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/sarvagya-pc/miniconda3/envs/featup/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
