### ISSUE TITLE
Errors in train_jbu_upsampler.py class

### ISSUE THREAD

**Issue by ArkashJ** [mhamilton723/FeatUp#74]
I'm trying to train FeatUp using my own Dinov2 backbone and added Featup as a git submodule to my repo. I then installed featup in editable mode and run train_jbu_upsampler. All the changes I implemented were in the hydra config (changing the model, number of iterations etc). Has anyone dealt with this error before?

 python3 train_jbu_upsampler.py 
Traceback (most recent call last):
  File "/nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/featup/train_jbu_upsampler.py", line 19, in <module>
    from featup.datasets.JitteredImage import apply_jitter, sample_transform
  File "/nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/featup/__init__.py", line 1, in <module>
    from featup.upsamplers import JBULearnedRange
  File "/nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/featup/upsamplers.py", line 7, in <module>
    from featup.adaptive_conv_cuda.adaptive_conv import AdaptiveConv
  File "/nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/featup/adaptive_conv_cuda/__init__.py", line 1, in <module>
    from .adaptive_conv import AdaptiveConv
  File "/nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/featup/adaptive_conv_cuda/adaptive_conv.py", line 4, in <module>
    import adaptive_conv_cuda_impl as cuda_impl
ImportError: /nfs/scratch1/ajain/cell_interactome/src/third_party/FeatUp/adaptive_conv_cuda_impl.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPKvmm

I was trying to find this issue but to no avail, also was looking at this thread - https://github.com/vllm-project/vllm/issues/2747

**Comment by ArkashJ** [comment]
It works now, I had to run `uv pip install vllm`.
