### ISSUE TITLE
Incorrect input size being output to CLIP?

### ISSUE THREAD

**Issue by kicks66** [mhamilton723/FeatUp#9]
im using the following code from the collab notebook:

```
import torch
import torchvision.transforms as T
from PIL import Image

from featup.util import norm, unnorm
from featup.plotting import plot_feats

input_size = 224
image_path = "sample-images/plant.png"

transform = T.Compose([
    T.Resize(input_size),
    T.CenterCrop((input_size, input_size)),
    T.ToTensor(),
    norm
])

image_tensor = transform(Image.open(image_path).convert("RGB")).unsqueeze(0).cuda()

upsampler = torch.hub.load("mhamilton723/FeatUp", 'clip').cuda()
hr_feats = upsampler(image_tensor)
lr_feats = upsampler.model(image_tensor)
plot_feats(unnorm(image_tensor)[0], lr_feats[0], hr_feats[0])
```

and getting the following error:

```
/home/ec2-user/venv/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/ec2-user/FeatUp/test.py", line 21, in <module>
    hr_feats = upsampler(image_tensor)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/.cache/torch/hub/mhamilton723_FeatUp_main/hubconf.py", line 19, in forward
    return self.upsampler(self.model(image), image)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/FeatUp/featup/upsamplers.py", line 271, in forward
    source_2 = self.upsample(source, guidance, self.up1)
  File "/home/ec2-user/FeatUp/featup/upsamplers.py", line 267, in upsample
    upsampled = up(source, small_guidance)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/FeatUp/featup/upsamplers.py", line 249, in forward
    return AdaptiveConv.apply(hr_source_padded, combined_kernel)
  File "/home/ec2-user/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ec2-user/FeatUp/featup/adaptive_conv_cuda/adaptive_conv.py", line 22, in forward
    result = cuda_impl.forward(input, filters)
RuntimeError: Unknown layout
```

**Comment by phdshliang** [comment]
Try torch 2.1.0 instead of other torch versions.
